add_header Cross-Origin-Opener-Policy same-origin always;
add_header Cross-Origin-Embedder-Policy require-corp always;
add_header Cross-Origin-Resource-Policy same-origin always;
add_header X-Content-Type-Options nosniff always;

types {
    application/manifest+json webmanifest;
    text/javascript mjs;
    application/wasm wasm;
    application/zip zip;
}
